name: Update Alcohol Origins GeoMap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # every hour, on the hour (UTC)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo (with default GITHUB_TOKEN credentials)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ensures GITHUB_TOKEN is used for any git push

      # 2) Reconstruct service-account JSON from secret
      - name: Write GCP Service Account JSON
        env:
          SA_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          echo "$SA_JSON" > ./alcohol-origins-geomap-cd20d437877f.json

      # 3) Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas folium gspread google-auth

      # 5) Run the mapping script
      - name: Generate updated map
        run: |
          python create_map.py

      # 6) Commit and push new docs/index.html if changed
      - name: Commit and push changes
        run: |
          # Configure commit author
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # Stage the updated file
          git add docs/index.html

          # If there are changes, commit and push
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-update map at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push origin main
          else
            echo "No changes to index.html; skipping commit and push."
          fi