name: Update Alcohol Origins GeoMap

# Grant the GITHUB_TOKEN write access so the workflow can push changes
permissions:
  contents: write

on:
  # Allow manual triggering via GitHub UI or API
  workflow_dispatch: {}
  # Run on every push to main
  push:
    branches:
      - main
  # Also run hourly on the hour (UTC)
  schedule:
    - cron: '0 * * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository with GITHUB_TOKEN for persistent credentials
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      # 2) Reconstruct service-account JSON from secret
      - name: Write GCP Service Account JSON
        env:
          SA_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          echo "$SA_JSON" > ./alcohol-origins-geomap-cd20d437877f.json

      # 3) Set up Python 3.10 environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 4) Install required Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas folium gspread google-auth

      # 5) Run the mapping script to regenerate docs/index.html
      - name: Generate updated map
        run: |
          python create_map.py

      # 6) Commit and push docs/index.html if it changed
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure commit author
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          # Stage the updated file
          git add docs/index.html

          # Only commit and push if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-update map at $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git push origin main
          else
            echo "No changes to index.html; skipping commit and push."
          fi