name: Update Alcohol Origins GeoMap

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Restore GCP service account key
        run: |
          cat << 'EOF' > ./alcohol-origins-geomap-cd20d437877f.json
          ${{ secrets.GCP_SERVICE_ACCOUNT }}
          EOF

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas folium gspread google-auth

      - name: Generate GeoMap
        run: python create_map.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAGES_PAT }}   # use your PAT, not GITHUB_TOKEN
          publish_dir: ./docs
          publish_branch: gh-pages